### PR TITLE
fix: make the USPhoneNumber custom validator example compile

### PR DESCRIPTION
**Pull request by djarnis73**
The example did not compile when copy-pasting into a project.

### CODE REVIEW

**Comment by kito99** [comment]
@djarnis73 thanks! Can you sign the Eclipse ECA? https://www.eclipse.org/legal/eca/faq/

**Comment by djarnis73** [comment]
I did sign it, but my original commit was done with the wrong email address. I have amended the commit with the correct email address and force pushed it, but it does not look like that gets picked up by this PR. So perhaps I will need to close and re-create this PR, what do you think?

**Comment by kito99** [comment]
@djarnis73 yes, that is probably the easiest thing to do. That's what I did the last time I had this problem.

**Comment by djarnis73** [comment]
Closing to re-create with correct commit email address.

**Pull request closed without merging**
